export async function lookupBias(article) {
  // Perform the bias lookup based on the article source
  const bias = {
      'ABC News': 'Lean Left',
      'Aberdeen News': 'Center',
      'Above The Law': 'Lean Left',
      'Abridge News': 'Mixed',
      'Addison County Independent': 'Center',
      'Adventist Today': 'Lean Left',
      'Advocate': 'Lean Left',
      'AframNews': 'Left',
      'African American Conservatives': 'Right',
      'Afro': 'Left',
      'Aiken Standard': 'Center',
      'AJ+': 'Left',
      'Akron Beacon Journal': 'Center',
      'Al Jazeera English': 'Lean Left',
      'Al Jazeera': 'Lean Left',
      'Alabama News Network': 'Center',
      'Alamosa News': 'Center',
      'Albany Democrat-Herald': 'Center',
      'Albert Lea Tribune': 'Center',
      'Albuquerque Journal': 'Center',
      'Alleghany News': 'Center',
      'AllSides': 'Mixed',
      'Alpha News': 'Right',
      'AlterNet': 'Left',
      'America\'s 1st Freedom': 'Lean Right',
      'American Greatness': 'Right',
      'American Press': 'Lean Left',
      'American Thinker': 'Right',
      'Anchorage Daily News': 'Center',
      'Anchorage Press': 'Center',
      'Anderson Independent-Mail': 'Center',
      'Aquinas College Saint': 'Left',
      'Arc Digital': 'Center',
      'Argus Leader': 'Center',
      'Arizona Daily Star': 'Center',
      'Arizona Mirror': 'Center',
      'Arkansas Democrat-Gazette': 'Left',
      'Ars Technica': 'Center',
      'Asbury Park Press': 'Center',
      'Associated Press': 'Center',
      'Atlanta Black Star': 'Lean Left',
      'Atlanta Journal-Constitution': 'Lean Left',
      'Attitude Magazine': 'Lean Left',
      'Austin American-Statesman': 'Lean Left',
      'Austin Daily Herald': 'Center',
      'Avenue News': 'Center',
      'Avoyelles Journal': 'Center',
      'Axios': 'Lean Left',
      'AZ Central': 'Center',
      'azcentral': 'Center',
      'Babylon Bee': 'Lean Right',
      'Baltimore Sun': 'Center',
      'Bangor Daily News': 'Lean Left',
      'Baptist News Global': 'Lean Left',
      'Baptist Press': 'Center',
      'Baptist Standard': 'Center',
      'Barnstable Patriot': 'Center',
      'Barron\'s': 'Center',
      'Bartlesville Examiner-Enterprise': 'Center',
      'BBC News': 'Center',
      'BBC': 'Center',
      'Bearing Drift': 'Right',
      'Beaumont Enterprise': 'Center',
      'Beaver County Times': 'Center',
      'Belleville News-Democrat': 'Center',
      'Bergen Record': 'Lean Left',
      'BET': 'Lean Left',
      'Beyond Today': 'Right',
      'Biblical Gender Roles': 'Right',
      'Biblical Sexology': 'Right',
      'Billings Gazette': 'Center',
      'Bing News': 'Lean Left',
      'Bizpac Review': 'Right',
      'Black Agenda Report': 'Left',
      'Black Community News': 'Right',
      'Black Enterprise': 'Lean Left',
      'Black News Channel': 'Lean Left',
      'Black News': 'Left',
      'Blavity': 'Left',
      'Block Club Chicago': 'Left',
      'Bloomberg Television': 'Lean Left',
      'Bloomberg': 'Lean Left',
      'Blue Virginia': 'Left',
      'Bluefield Daily Telegraph': 'Center',
      'Boing Boing': 'Left',
      'Bolts': 'Left',
      'Bonner County Daily Bee': 'Center',
      'BorderReport': 'Center',
      'Boston Herald': 'Lean Right',
      'Boston Review': 'Lean Left',
      'Bowling Green Daily News': 'Lean Left',
      'Box Elder News Journal': 'Center',
      'Bozeman Daily Chronicle': 'Center',
      'Breitbart News': 'Right',
      'Bridgemi.com': 'Center',
      'Brown Girl Magazine': 'Left',
      'Brownstone Institute': 'Right',
      'Brush News-Tribune': 'Center',
      'Burlington County Times': 'Center',
      'Burlington Free Press': 'Center',
      'Business Insider': 'Lean Left',
      'Bustle': 'Lean Left',
      'BuzzFeed News': 'Left',
      'Byron Donalds': 'Lean Right',
      'C-SPAN': 'Center',
      'CalMatters': 'Center',
      'CalWatchdog': 'Center',
      'Cape Cod Times': 'Center',
      'Cape Gazette': 'Center',
      'Capital & Main': 'Lean Left',
      'Capitol Weekly': 'Center',
      'Care2': 'Left',
      'Carlsbad Current-Argus': 'Center',
      'Carriage Towne News': 'Center',
      'Casper Star-Tribune': 'Center',
      'Catholic Digest': 'Lean Right',
      'Catholic News Agency': 'Right',
      'Catholic News Service': 'Center',
      'CBC News': 'Lean Left',
      'CBN': 'Right',
      'CBS News': 'Lean Left',        
      'CBS': 'Lean Left',
      'Cecil Whig': 'Center',
      'Center for Public Integrity': 'Lean Left',
      'Center Post Dispatch': 'Center',
      'Centre View': 'Lean Left',
      'Chalkbeat': 'Center',
      'Charisma Magazine': 'Right',
      'Charleston City Paper': 'Center',
      'Chattanooga Times Free Press': 'Center',
      'Chicago Crusader': 'Left',
      'Chicago Defender': 'Left',
      'Chicago Sun-Times': 'Lean Left',
      'Chicago Tribune': 'Center',
      'Christian Coalition of America': 'Lean Right',
      'Christian Headlines': 'Center',
      'Christian News Network': 'Right',
      'Christian News Now': 'Lean Right',
      'Christian Science Monitor': 'Center',
      'Christianity Today': 'Lean Right',
      'Church Militant': 'Right',
      'ChurchLeaders.com': 'Center',
      'Cincinnati Enquirer': 'Center',
      'City Journal': 'Right',
      'Clarksdale Press Register': 'Center',
      'cleveland.com': 'Center',
      'Clinton Herald': 'Center',
      'CNBC Television': 'Center',
      'CNBC': 'Center',
      'CNET': 'Center',
      'CNN Business': 'Lean Left',
      'CNN': 'Lean Left',
      'CNSNews.com': 'Right',
      'Cody Enterprise': 'Center',
      'CoinDesk': 'Center',
      'Colorado Springs Gazette': 'Center',
      'Columbia Daily Tribune': 'Center',
      'Columbia Journalism Review': 'Center',
      'Columbia Missourian': 'Center',
      'Commentary Magazine': 'Right',
      'Commerce City Sentinel Express': 'Center',
      'Common Dreams': 'Left',
      'Complex': 'Center',
      'Concord Monitor': 'Center',
      'Connecticut Post': 'Center',
      'Conservative HQ': 'Right',
      'Cook Report': 'Center',
      'Corvallis Gazette-Times': 'Center',
      'Counter Currents': 'Lean Left',
      'Counterpointing': 'Mixed',
      'Courier-Post': 'Center',
      'Cowboy State Daily': 'Lean Right',
      'CrowdPAC': 'Center',
      'Crunchbase News': 'Center',
      'CU Independent': 'Center',
      'Cumberland Times-News': 'Center',
      'Current Affairs': 'Left',
      'Daily Breeze': 'Center',
      'Daily Cardinal': 'Center',
      'Daily Chela': 'Left',
      'Daily Citizen': 'Right',
      'Daily Corinthian': 'Center',
      'Daily Journal': 'Center',
      'Daily Kos': 'Left',
      'Daily Mail': 'Right',
      'Daily Memphian': 'Center',
      'Daily News-Record': 'Center',
      'Daily Norseman': 'Center',
      'Daily Northwestern': 'Lean Left',
      'Daily Press': 'Lean Right',
      'Daily Progress': 'Center',
      'Daily Targum': 'Lean Left',
      'DailyTrib.com': 'Center',
      'Dayton Daily News': 'Center',
      'DCist': 'Center',
      'Deadline': 'Center',
      'Defense One': 'Center',
      'Delaware State News': 'Center',
      'Delta Democrat Times': 'Center',
      'Democracy Now!': 'Left',
      'Democrat and Chronicle': 'Center',
      'Derry News': 'Center',
      'Des Moines Register': 'Center',
      'Deseret News': 'Center',
      'Desiring God': 'Lean Right',
      'DeSmog': 'Lean Left',
      'Detroit Free Press': 'Lean Left',
      'Detroit Lakes Tribune': 'Center',
      'Detroit News': 'Center',
      'Deutsche Welle': 'Center',
      'Diplomatic Courier': 'Center',
      'Divided We Fall': 'Mixed',
      'Drudge Report': 'Lean Right',
      'Duke Chronicle': 'Center',
      'DW (English)': 'Center',
      'DW News': 'Center',
      'East Bay Times': 'Lean Left',
      'East Oregonian': 'Center',
      'Ebony': 'Left',
      'Eden Prairie Local News': 'Center',
      'Education Week': 'Center',
      'El Paso Times': 'Center',
      'Elle Magazine': 'Lean Left',
      'Emporia Gazette': 'Center',
      'Erie Gay News': 'Lean Left',
      'Erraticus': 'Center',
      'ESPN.com': 'Lean Left',
      'Esquire': 'Left',
      'Estes Park Trail Gazette': 'Center',
      'Eurek Alert': 'Center',
      'Evansville Courier & Press': 'Center',
      'Evie Magazine': 'Lean Right',
      'FAIR': 'Lean Left',
      'Fairmont Sentinel': 'Center',
      'Falls Church News - Press': 'Left',
      'Financial Times': 'Center',
      'Fiscal Times': 'Lean Right',
      'FiveThirtyEight': 'Center',
      'Florida Politics': 'Center',
      'Floyd County Chronicle & Times': 'Center',
      'Forbes': 'Center',
      'Foreign Affairs': 'Center',
      'Foreign Policy': 'Center',
      'Fort Worth Star-Telegram': 'Center',
      'Fortune': 'Center',
      'Fox Business': 'Lean Right',
      'Fox News Latino': 'Right',
      'Fox News': 'Right',
      'Fox21': 'Center',
      'Fox9': 'Center',
      'Franklin Favorite': 'Center',
      'Frederick News-Post': 'Center',
      'FrontPage Magazine': 'Right',
      'Gainesville Sun': 'Center',
      'Gallatin News': 'Center',
      'Gay City News': 'Lean Left',
      'Gay Times': 'Lean Left',
      'GayBuzzer': 'Center',
      'GayNewsToday': 'Left',
      'GayStarNews': 'Left',
      'Georgia Asian Times': 'Center',
      'Georgia Recorder': 'Center',
      'Georgia Voice': 'Left',
      'Gillette News Record': 'Center',
      'Gizmodo': 'Lean Left',
      'GLAAD': 'Lean Left',
      'Global News': 'Lean Left',
      'GoLocal Providence': 'Center',
      'Good Faith Media': 'Lean Left',
      'Good News Magazine': 'Lean Right',
      'Google News': 'Lean Left',
      'Gothamist': 'Center',
      'GQ.com': 'Lean Left',
      'Green Bay Press-Gazette': 'Center',
      'Greenfield Daily Reporter': 'Center',
      'Greenwich Time': 'Center',
      'Grid': 'Lean Left',
      'Grist': 'Lean Left',
      'Haaretz': 'Center',
      'Hampton Roads Messanger': 'Center',
      'Harrison Daily Times': 'Center',
      'Hartford Courant': 'Center',
      'Harvard Business School': 'Lean Left',
      'Hastings Tribune': 'Center',
      'Hattiesburg American': 'Center',
      'Hawaii News Now': 'Center',
      'Hawaii Tribune-Herald': 'Center',
      'Heavy.com': 'Center',
      'Herald Democrat': 'Left',
      'Herald-Dispatch': 'Lean Left',
      'Herald-Tribune': 'Lean Left',
      'High Point Enterprise': 'Center',
      'High Times': 'Lean Left',
      'Hindustan Times': 'Center',
      'Hip Latina': 'Left',
      'Hobbs News-Sun': 'Center',
      'Homeland Security Today': 'Lean Left',
      'Homer News': 'Center',
      'Honolulu Civil Beat': 'Center',
      'Honolulu Star-Advertiser': 'Center',
      'Hot Springs Sentinel-Record': 'Center',
      'HotAir': 'Lean Right',
      'Houston Chronicle': 'Center',
      'HuffPost': 'Left',
      'Human Events': 'Lean Right',
      'Idaho Press': 'Center',
      'Idaho State Journal': 'Center',
      'Idaho Statesman': 'Center',
      'Inacow': 'Right',
      'IncentFit': 'Center',
      'Independent Journal Review': 'Lean Right',
      'Independent Record': 'Center',
      'Indiana Daily Student': 'Center',
      'Indy Online': 'Center',
      'Indy Week': 'Lean Left',
      'IndyStar': 'Center',
      'InfoWars': 'Right',
      'Inland Valley Daily Bulletin': 'Center',
      'Inside Higher Ed': 'Lean Left',
      'Inside Philanthropy': 'Center',
      'Insider': 'Lean Left',
      'Intellectual Conservative': 'Lean Right',
      'International Business Times': 'Center',
      'Investopedia': 'Center',
      'Investor\'s Business Daily': 'Lean Right',
      'Iowa Capital Dispatch': 'Center',
      'IVN': 'Center',
      'Jackson Hole News&Guide': 'Center',
      'Jacobin': 'Left',
      'Jamestown Press': 'Center',
      'Jefferson City News Tribune': 'Center',
      'Jefferson Public Radio': 'Center',
      'Jewish Insider': 'Center',
      'Jezebel': 'Left',
      'JoeMyGod': 'Left',
      'Journalist\'s Resource': 'Center',
      'JRL Charts': 'Left',
      'JSTOR Daily': 'Center',
      'Jubilee Media': 'Center',
      'Judicial Watch': 'Lean Right',
      'Just Security': 'Center',
      'Just The News': 'Center',
      'KALW.org': 'Center',
      'Kane County Chronicle': 'Center',
      'Kansas Reflector': 'Left',
      'KARE11': 'Center',
      'KARK 4 News': 'Lean Left',
      'KATU': 'Center',
      'Kearney Hub': 'Center',
      'Keeping it Right': 'Right',
      'Kennebec Journal': 'Center',
      'Kenosha News': 'Center',
      'Kent County Daily Times': 'Center',
      'Kent Island Bay Times': 'Center',
      'Kentucky Gazette': 'Center',
      'Kilgore News Herald': 'Center',
      'Kingsport Times-News': 'Center',
      'Knoxville News Sentinel': 'Center',
      'KNSI Radio': 'Center',
      'KQED': 'Center',
      'KSL': 'Right',
      'KSTP': 'Center',
      'KTOO': 'Center',
      'KTTC News': 'Center',
      'KVRR': 'Center',
      'KWCH': 'Center',
      'La Crosse Tribune': 'Center',
      'LA Sentinel': 'Left',
      'Laramie Boomerang': 'Center',
      'Laredo Morning Times': 'Lean Left',
      'Las Cruces Sun-News': 'Center',
      'Las Vegas Review-Journal': 'Center',
      'Las Vegas Sun': 'Lean Left',
      'Latino Rebels': 'Left',
      'Law & Crime': 'Center',
      'Lawfare': 'Center',
      'Lawton Constitution': 'Center',
      'Leader-Telegram': 'Center',
      'Leafly': 'Left',
      'Leesburg Today': 'Lean Right',
      'Lewiston Tribune': 'Center',
      'Lexington Herald-Leader': 'Center',
      'LGBTQ Nation': 'Left',
      'Lifehacker': 'Center',
      'Live Action News': 'Lean Right',
      'Live Science': 'Center',
      'Living Lutheran': 'Center',
      'Log Cabin': 'Right',
      'Logan Banner': 'Center',
      'Long Beach Press-Telegram': 'Center',
      'Longmont Times-Call': 'Lean Left',
      'Los Angeles Daily News': 'Center',
      'Los Angeles Times': 'Lean Left',
      'Lovell Chronicle': 'Center',
      'Maine Beacon': 'Lean Left',
      'Mankato Free Press': 'Lean Left',
      'Marijuana Moment': 'Lean Left',
      'MarketWatch': 'Center',
      'Mashable': 'Left',
      'MassLive.com': 'Lean Left',
      'McClatchyDC': 'Center',
      'McKenzie County Farmer': 'Center',
      'Meade County Messenger': 'Center',
      'Meaws': 'Lean Left',
      'Media Matters': 'Left',
      'Media Research Center': 'Right',
      'Media Village': 'Center',
      'Mediaite': 'Lean Left',
      'Meridian Magazine': 'Lean Right',
      'Metro Weekly': 'Left',
      'Mexico Daily Post': 'Center',
      'Mexico News Daily': 'Center',
      'Miami Herald': 'Lean Left',
      'MichelleMalkin.com': 'Right',
      'Michigan Daily': 'Lean Left',
      'MidWeek': 'Center',
      'Military Times': 'Center',
      'Milwaukee Journal Sentinel': 'Center',
      'Minnesota Lawyer': 'Center',
      'Minnesota Native News': 'Center',
      'Minnesota News Network': 'Center',
      'Minnesota Public Radio': 'Center',
      'Minnesota Reformer': 'Left',
      'Minnesota Spokesman Reporter': 'Center',
      'MinnPost': 'Center',
      'MinnPost': 'Center',
      'Misinformation Review': 'Center',
      'Mismatch.org': 'Mixed',
      'Mississippi Free Press': 'Lean Left',
      'Mississippi Today': 'Center',
      'Missoulian': 'Center',
      'MIT News': 'Center',
      'Mitú': 'Left',
      'MLive.com': 'Center',
      'Monadnock Ledger-Transcript': 'Center',
      'Montana Free Press': 'Center',
      'Morgan Messenger': 'Center',
      'Morning Brew': 'Lean Left',
      'Mother Jones': 'Left',
      'Mountain State Spotlight': 'Center',
      'MSNBC': 'Left',
      'MTV News Online': 'Lean Left',
      'Muscatine Journal': 'Center',
      'Naples Daily News': 'Center',
      'National Catholic Register': 'Right',
      'National Geographic': 'Center',
      'National Journal': 'Center',
      'National Post': 'Lean Right',
      'National Review': 'Right',
      'Nature.com': 'Center',
      'Nautilus Quarterly': 'Center',
      'NBC News': 'Lean Left',
      'Nevada Appeal': 'Center',
      'Nevada Appeal': 'Center',
      'New Discourses': 'Center',
      'New Hampshire Public Radio': 'Center',
      'New Hampshire Union Leader': 'Center',
      'New Haven Register': 'Center',
      'New Jersey Globe': 'Center',
      'New Jersey Monitor': 'Lean Left',
      'New Mexico In Depth': 'Center',
      'New Pittsburgh': 'Left',
      'New Republic': 'Left',
      'New Rockford Transcript': 'Center',
      'New York Daily News': 'Left',
      'New York Focus': 'Center',
      'New York Magazine': 'Left',
      'New York Post': 'Lean Right',
      'New York Times': 'Lean Left',
      'Newark Post': 'Center',
      'News & Citizen': 'Center',
      'News Center Maine': 'Lean Left',
      'News One': 'Lean Left',
      'NewsBusters': 'Right',
      'Newsday': 'Center',
      'Newsmax (News)': 'Right',
      'NewsNation': 'Center',
      'NewsOne': 'Left',
      'Newsweek': 'Center',
      'Newtrals': 'Center',
      'Nicholas Chronicle': 'Center',
      'Nieman Lab': 'Center',
      'nj.com': 'Lean Left',
      'NMPolitics.net': 'Center',
      'Norfolk Daily News': 'Center',
      'North Wright County Today': 'Center',
      'NowThis News': 'Lean Left',
      'NPR': 'Lean Left',
      'NTD': 'Lean Right',
      'Nutfield News': 'Center',
      'NYNMedia': 'Left',
      'Occupy Democrats': 'Left',
      'Ohio Capital Journal': 'Lean Left',
      'OilPrice.com': 'Center',
      'Omaha World-Herald': 'Center',
      'One America News Network': 'Right',
      'One Nation News': 'Lean Left',
      'Orange County Register': 'Lean Right',
      'Oregon Public Broadcasting ': 'Center',
      'Ottumwa Courier': 'Center',
      'Ouachita Citizen': 'Center',
      'Our.News': 'Center',
      'Out In Jersey': 'Lean Left',
      'Out': 'Left',
      'Outkick the Coverage': 'Center',
      'Pacific Standard': 'Lean Left',
      'Pahrump Valley Times': 'Center',
      'Paintsville Herald': 'Center',
      'Palladium Magazine': 'Center',
      'Palm Springs Desert Sun': 'Center',
      'Park Record': 'Center',
      'Pasadena Star-News': 'Center',
      'Patch.com': 'Center',
      'PBS NewsHour': 'Lean Left',
      'Pea Ridge Times': 'Center',
      'Peacock Panache': 'Left',
      'Peninsula Clarion': 'Center',
      'Pennsylvania Capital-Star': 'Lean Right',
      'Pensacola News Journal': 'Center',
      'People': 'Lean Left',
      'Peoria Journal Star': 'Center',
      'Persuasion': 'Lean Left',
      'Philadelphia Gay News': 'Lean Left',
      'Phoenix New Times': 'Center',
      'Phys.org': 'Center',
      'Physicians for Life': 'Lean Right',
      'PinkNews': 'Left',
      'Pioneer Press': 'Center',
      'Pittsburgh Post-Gazette': 'Center',
      'Pittsburgh Tribune-Review': 'Center',
      'PJ Media': 'Right',
      'Plainsman': 'Center',
      'Plaquemines Gazette': 'Center',
      'POLITICO Europe': 'Lean Left',
      'POLITICO': 'Lean Left',
      'PoliticusUSA': 'Left',
      'Pope County Tribune': 'Center',
      'Portland Press Herald': 'Center',
      'Post Register': 'Center',
      'Post-Bulletin': 'Center',
      'Poughkeepsie Journal': 'Center',
      'Poynter': 'Center',
      'Premier Christian News': 'Lean Left',
      'PRI (Public Radio International)': 'Center',
      'Progressive Voices of Iowa': 'Left',
      'Project Veritas': 'Right',
      'ProPublica': 'Lean Left',
      'Psych Central': 'Center',
      'Psychology Today': 'Center',
      'Public News Service': 'Center',
      'Public News Service': 'Center',
      'Quartz': 'Center',
      'Queerty': 'Left',
      'Quillette': 'Lean Right',
      'Rapid City Journal': 'Center',
      'Rasmussen Reports': 'Lean Right',
      'Raw Story': 'Left',
      'Reading Eagle': 'Center',
      'RealClearPolitics': 'Center',
      'Reason': 'Lean Right',
      'Record Journal': 'Center',
      'Record-Courier': 'Center',
      'Red Lake Nation News': 'Center',
      'Red Racing Horses': 'Right',
      'Redlands Daily Facts': 'Center',
      'RedState': 'Right',
      'Refinery29': 'Left',
      'Relevant Magazine': 'Lean Left',
      'Religion News Service': 'Center',
      'Reno News & Review': 'Center',
      'Reuters': 'Center',
      'Reuters.com': 'Center',
      'Revolver News': 'Right',
      'Richmond Times Dispatch': 'Lean Right',
      'Right Side News': 'Right',
      'Right Wing News': 'Right',
      'Risen Magazine': 'Center',
      'Rogue River Press': 'Center',
      'Roll Call': 'Center',
      'RollingStone.com': 'Left',
      'RT': 'Lean Right',
      'Ruston Daily Leader': 'Center',
      'Rutland Herald': 'Center',
      'Sacramento Bee': 'Lean Left',
      'Salina Journal': 'Center',
      'Salon': 'Left',
      'San Antonio Express-News': 'Center',
      'San Bernardino Sun': 'Center',
      'San Diego Union-Tribune': 'Lean Left',
      'San Francisco Chronicle': 'Left',
      'San Gabriel Valley Tribune': 'Center',
      'San Jose Mercury News': 'Lean Left',
      'Santa Fe New Mexican': 'Center',
      'Science Daily': 'Center',
      'Scientific American': 'Lean Left',
      'Scottsbluff Star-Herald': 'Center',
      'SCOTUSblog': 'Center',
      'Scriberr Media - News': 'Center',
      'Scripps News': 'Center',
      'Searchlight New Mexico': 'Center',
      'Seattle Gay News': 'Lean Left',
      'Semafor': 'Lean Left',
      'SF Weekly': 'Center',
      'SFGATE': 'Lean Left',
      'Shreveport Times': 'Center',
      'Silive.com': 'Center',
      'Silver City Daily Press': 'Center',
      'Sky-Hi Daily News': 'Lean Left',
      'Slate': 'Left',
      'Smerconish': 'Center',
      'Smithsonian Magazine': 'Center',
      'Socialist Alternative': 'Left',
      'Socialist Project/The Bullet': 'Left',
      'South Bend Tribune': 'Center',
      'South China Morning Post': 'Center',
      'South Florida Gay News': 'Lean Left',
      'Southeast Missourian': 'Center',
      'Southern Minnesota News': 'Center',
      'Southern Utah News': 'Center',
      'Sparks Tribune': 'Center',
      'Spiked': 'Lean Right',
      'Splinter': 'Left',
      'Spokesman Review': 'Lean Left',
      'Spotlight PA': 'Center',
      'Springfield News-Leader': 'Center',
      'St. Augustine Record': 'Center',
      'St. Cloud Times': 'Lean Left',
      'St. George News': 'Center',
      'St. Joseph News-Press': 'Center',
      'St. Louis Post-Dispatch': 'Center',
      'Stamford Advocate': 'Center',
      'Star Tribune': 'Lean Left',
      'Stars and Stripes': 'Center',
      'STAT': 'Center',
      'State Journal': 'Lean Left',
      'Statesman Journal': 'Center',
      'Stillwater Gazette': 'Center',
      'Storm Lake Times': 'Center',
      'StoryCorps': 'Mixed',
      'Students For Life': 'Lean Right',
      'Subverse': 'Center',
      'Sun Herald ': 'Center',
      'Sun Sentinel': 'Center',
      'Suspend Belief Podcast': 'Mixed',
      'Tablet Mag': 'Lean Right',
      'Taipei Times': 'Center',
      'Tallahassee Democrat': 'Center',
      'Tampa Bay Times': 'Center',
      'Tangle': 'Center',
      'Tech Xplore': 'Center',
      'TechCrunch': 'Center',
      'Telegram & Gazette': 'Center',
      'Texas Monthly': 'Center',
      'Texas Signal': 'Left',
      'The Ada News': 'Center',
      'The Advocate-Messenger': 'Lean Left',
      'The Advocate': 'Lean Left',
      'The American Conservative': 'Right',
      'The American Mind': 'Lean Right',
      'The American Spectator': 'Right',
      'The Anniston Star': 'Center',
      'The Appeal': 'Center',
      'The Ardmoreite': 'Center',
      'The Associated Press': 'Center',
      'The Atlantic': 'Left',
      'The Bellows': 'Center',
      'The Berkshire Eagle': 'Lean Left',
      'The Bismarck Tribune': 'Center',
      'The Black Detour': 'Center',
      'The Blade': 'Center',
      'The Blaze': 'Right',
      'The Boston Globe': 'Left',
      'The Brazilian Report': 'Center',
      'The Buffalo News': 'Center',
      'The Bulwark': 'Lean Right',
      'The Cadiz Record': 'Lean Left',
      'The Californian': 'Center',
      'The Canyon County Zephyr': 'Left',
      'The Center Square - Michigan': 'Center',
      'The Center Square - Minnesota': 'Center',
      'The Center Square - Texas': 'Center',
      'The Center Square': 'Center',
      'The Christian Century': 'Lean Left',
      'The Christian Left Blog': 'Left',
      'The Christian Post': 'Lean Right',
      'The City ': 'Lean Left',
      'The Clarion-Ledger': 'Center',
      'The Colebrook Chronicle': 'Center',
      'The College Fix': 'Right',
      'The Colorado Sun': 'Lean Left',
      'The Columbian': 'Center',
      'The Columbus Dispatch': 'Center',
      'The Commercial Appeal': 'Lean Left',
      'The Conscious Conservative': 'Right',
      'The Conversation': 'Lean Left',
      'The Corpus Christi Caller-Times': 'Center',
      'The Courier-Journal': 'Lean Left',
      'The Courier-Tribune': 'Center',
      'The Current': 'Center',
      'The Daily Advance': 'Center',
      'The Daily Beast': 'Left',
      'The Daily Caller': 'Right',
      'The Daily Dot': 'Lean Left',
      'The Daily Herald': 'Center',
      'The Daily Iberian': 'Center',
      'The Daily Iowan': 'Center',
      'The Daily Mail': 'Right',
      'The Daily Nonpareil': 'Center',
      'The Daily Signal': 'Right',
      'The Daily Wire': 'Right',
      'The Daily Yonder': 'Center',
      'The Dallas Morning News': 'Center',
      'The Delaware County Daily Times': 'Lean Left',
      'The Delaware Wave': 'Center',
      'The Denver North Star': 'Center',
      'The Denver Post': 'Center',
      'The Dispatch': 'Lean Right',
      'The East Valley Tribune': 'Center',
      'The Economist': 'Lean Left',
      'The Ellsworth American': 'Center',
      'The Epoch Times': 'Lean Right',
      'The Federalist': 'Right',
      'The Flip Side': 'Mixed',
      'The Florida Capital Star': 'Right',
      'The Forum of Fargo-Moorhead': 'Center',
      'The Free Lance–Star': 'Center',
      'The Free Press': 'Center',
      'The Fulcrum': 'Center',
      'The Gateway Pundit': 'Right',
      'The Georgia Star News': 'Right',
      'The Globe and Mail': 'Center',
      'The Grio': 'Lean Left',
      'The Guardian UK': 'Lean Left',
      'The Guardian US': 'Lean Left',
      'The Guardian': 'Lean Left',
      'The HighWire': 'Lean Right',
      'The Hill': 'Center',
      'The Hollywood Reporter': 'Lean Left',
      'The Huntsville Item': 'Center',
      'The Hutchinson News': 'Center',
      'The Imaginative Conservative': 'Right',
      'The Independent': 'Lean Left',
      'The Intercept': 'Left',
      'The Iowa Torch': 'Lean Right',
      'The Irish Times': 'Center',
      'The Japan Times': 'Center',
      'The Jerusalem Post': 'Center',
      'The Journal Gazette': 'Center',
      'The Journal Times': 'Center',
      'The Juggernaut': 'Left',
      'The Justice': 'Lean Left',
      'The Kansas City Beacon': 'Center',
      'The Kansas City Star': 'Center',
      'The Korea Herald': 'Center',
      'The Kyiv Independent': 'Center',
      'The Leaf-Chronicle': 'Center',
      'The Libertarian Republic': 'Lean Right',
      'The Lincoln Project': 'Mixed',
      'The Lufkin Daily News': 'Center',
      'The Maine Monitor ': 'Lean Left',
      'The Maine Wire': 'Right',
      'The Maneater': 'Lean Left',
      'The Manila Times': 'Center',
      'The Markup': 'Center',
      'The Marshall Project': 'Center',
      'The Maui News': 'Center',
      'The McLeod County Chronicle': 'Center',
      'The Messenger': 'Center',
      'The Michigan Star': 'Right',
      'The Minnesota Daily': 'Lean Left',
      'The Minority Eye': 'Left',
      'The Montana Standard': 'Center',
      'The Narratives Project': 'Center',
      'The Nation': 'Left',
      'The National Pulse': 'Right',
      'The Nevada Independent': 'Center',
      'The New Orleans Advocate': 'Center',
      'The New York Times': 'Lean Left',
      'The New Yorker': 'Left',
      'The Newport Daily News': 'Center',
      'The News & Observer': 'Center',
      'The News Journal': 'Center',
      'The News Tribune': 'Center',
      'The Nome Nugget': 'Center',
      'The Observer': 'Center',
      'The Oklahoman': 'Center',
      'The Olympian': 'Center',
      'The Onion': 'Lean Left',
      'The Oracle': 'Center',
      'The Oregonian': 'Center',
      'The Palm Beach Post': 'Center',
      'The Pantagraph': 'Center',
      'The Patriot Ledger': 'Center',
      'The Patriot Post': 'Right',
      'The Patriot-News': 'Center',
      'The Penobscot Times': 'Center',
      'The Philadelphia Inquirer': 'Lean Left',
      'The Philly Tribune': 'Left',
      'The Plain Dealer': 'Center',
      'The Police Tribune': 'Lean Right',
      'The Portsmouth Herald': 'Center',
      'The Post and Courier ': 'Lean Right',
      'The Post Millennial': 'Lean Right',
      'The Post-Star': 'Center',
      'The Presbyterian Outlook': 'Lean Left',
      'The Prescott Times': 'Center',
      'The Press of Atlantic City': 'Center',
      'The Press-Enterprise': 'Lean Right',
      'The Providence Journal': 'Center',
      'The Red and Black': 'Center',
      'The Register-Guard': 'Center',
      'The Reliable Bias': 'Center',
      'The Reno Gazette-Journal': 'Lean Left',
      'The Republican Journal': 'Lean Right',
      'The Republican': 'Center',
      'The Resurgent': 'Right',
      'The Richfield Reaper': 'Center',
      'The Ripon Advance': 'Lean Right',
      'The Roanoke Times': 'Center',
      'The Root': 'Lean Left',
      'The Salt Lake Tribune': 'Lean Left',
      'The San Francisco Standard': 'Center',
      'The Saturday Evening Post': 'Center',
      'The Seattle Times': 'Center',
      'The South African': 'Center',
      'The Spectator World': 'Right',
      'The State Journal-Register': 'Center',
      'The State': 'Center',
      'The State': 'Lean Right',
      'The Sun News': 'Center',
      'The Sun': 'Center',
      'The Telegraph': 'Lean Right',
      'The Tennessean': 'Center',
      'The Texan': 'Lean Right',
      'The Texas Observer': 'Lean Left',
      'The Texas Tribune': 'Lean Left',
      'The Times and Democrat': 'Center',
      'The Times of Northwest Indiana': 'Center',
      'The Times of Israel': 'Center',
      'The Times-Independent': 'Center',
      'The Times-Picayune': 'Center',
      'The Times': 'Center',
      'The TimesDaily': 'Center',
      'The Topeka Capital-Journal': 'Center',
      'The Trentonian': 'Center',
      'The Verge': 'Lean Left',
      'The Vindicator': 'Center',
      'The Virginia Gazette': 'Center',
      'The Virginian-Pilot': 'Center',
      'The Wall Street Journal': 'Center',
      'The Walsh County Record': 'Center',
      'The Washington Informer': 'Lean Left',
      'The Washington Post': 'Lean Left',
      'The Washington Sun': 'Center',
      'The Week - News': 'Lean Left',
      'The Weekly Packet': 'Center',
      'The Weekly Standard': 'Right',
      'The Weirton Daily Times': 'Center',
      'The Westerly Sun': 'Center',
      'The Western Journal': 'Right',
      'The Wichita Eagle': 'Center',
      'The Wyoming Tribune Eagle': 'Center',
      'The Young Turks': 'Left',
      'TheGailyGrind': 'Left',
      'Them': 'Lean Left',
      'theSkimm': 'Lean Left',
      'ThinkProgress': 'Left',
      'THV11': 'Center',
      'Time Magazine': 'Lean Left',
      'Times Argus': 'Center',
      'Times Union': 'Center',
      'TODAY': 'Lean Left',
      'Toronto Star': 'Center',
      'Townhall': 'Right',
      'Trains.com': 'Center',
      'Trans Writes': 'Lean Left',
      'Tri-City Herald': 'Center',
      'Truthdig': 'Left',
      'TruthOut': 'Lean Left',
      'Tulsa World': 'Center',
      'Tuscaloosa News': 'Center',
      'Twin Cities PBS': 'Center',
      'Twin Cities Pioneer Press': 'Center',
      'Twin City Times': 'Center',
      'U.S. News & World Report': 'Lean Left',
      'UnHerd': 'Lean Right',
      'United Methodist Insight': 'Left',
      'United Methodist News': 'Lean Left',
      'United Press International': 'Center',
      'Univision': 'Lean Left',
      'Upward News ': 'Lean Right',
      'Upworthy': 'Left',
      'USA TODAY': 'Lean Left',
      'Vanity Fair': 'Lean Left',
      'Variety': 'Center',
      'Vatican News': 'Lean Right',
      'Vermont Standard': 'Center',
      'Vice': 'Left',
      'Virginia Center for Investigative Journalism': 'Lean Left',
      'Virginia Mercury': 'Center',
      'Virtue Online': 'Right',
      'Vogue': 'Left',
      'Voice of America': 'Center',
      'Volante': 'Center',
      'Votebeat': 'Center',
      'Vox.com': 'Left',
      'Vox': 'Left',
      'VT Digger': 'Lean Left',
      'Wake Up to Politics': 'Center',
      'Wall Street Journal': 'Center',
      'WANDTV': 'Center',
      'Washington Blade': 'Lean Left',
      'Washington City Paper': 'Center',
      'Washington Diplomat': 'Center',
      'Washington Examiner': 'Lean Right',
      'Washington Free Beacon': 'Right',
      'Washington Monthly': 'Lean Left',
      'Washington Times': 'Lean Right',
      'Watchdog.org': 'Lean Right',
      'WBUR': 'Center',
      'WCVB': 'Center',
      'WDSU': 'Center',
      'West Hawaii Today': 'Center',
      'West Texas Tribune': 'Center',
      'Weston Democrat': 'Center',
      'WFAE': 'Center',
      'WFSA': 'Lean Left',
      'WGBH': 'Center',
      'WGN': 'Center',
      'Whatfinger News': 'Right',
      'Whittier Daily News': 'Center',
      'Winona Daily': 'Center',
      'Winona Times': 'Center',
      'Wired': 'Center',
      'Wisconsin Gazette': 'Lean Left',
      'Wisconsin State Journal': 'Center',
      'WND': 'Right',
      'WNYC': 'Lean Left',
      'World Magazine': 'Right',
      'Worthy News': 'Center',
      'WVNews.com': 'Center',
      'WyoFile': 'Lean Right',
      'Wyoming Public Media': 'Lean Left',
      'Yahoo News': 'Left',
      'Yahoo! The 360': 'Mixed',
      'Yakima Herald-Republic': 'Center',
      'Yes! Magazine': 'Left',
      'York Dispatch': 'Center',
      'Yuma Sun': 'Center',
      'ZeroHedge': 'Lean Right',
  }
  const source = article.source.trim();
  if (Object.hasOwnProperty.call(bias, source)) {
    article.bias = bias[source]; // Add the bias to the article object
  }
};